---
  # setup_orca_admin variables
  orka_admin_password: $1$SomeSalt$W98.5N4Mc2EpxOTlI9MI20
  create_orka_admin: False
  # PostgreSql variables
  eco_db_user: hduser
  eco_db_password: hdpass
  hue_db_name: hduser
  hue_home: /usr/local/hue
  hive_db_name: metastore
  hive_home: /usr/local/hive
  choose_role: webserver

  # Hadoop-yarn variables
  path_to_common_libs: /usr/local/hadoop/share/hadoop/common
  path_to_hdfs_libs: /usr/local/hadoop/share/hadoop/hdfs/lib
  hadoopuser_path: /home/hduser
  cloudera_bin: /usr/bin
  manage_cluster: placeholder
  livy_server_script: cloudera_livy.sh
  is_master: False
  is_slave: False
  dfs_replication: 2
  dfs_blocksize: 128m
  filename: /home/hduser/.ssh/id_rsa
  etchosts_filename: /etc/hosts_2 
  yarn_common_url: http://archive.apache.org/dist/hadoop/common
  yarn_version: hadoop-2.5.2
  path_to_hadoop: /usr/local
  hadoop_home: "{{path_to_hadoop}}/hadoop"
  path: ~/.ssh/id_rsa.pub
  master_key_hduser: master_{{ hostvars[groups['master'][0]].inventory_hostname_short}}_pub_key_hduser
  master_key_root: master_{{ hostvars[groups['master'][0]].inventory_hostname_short}}_pub_key_root
  master_key_cloudera: master_{{ hostvars[groups['master_cloud'][0]].inventory_hostname_short}}_pub_key_root
  ssh_file_name: no_ssh_key_selected