---
- name: Setting up common tasks for every host 
  hosts: all
  remote_user: root
  roles:
     - commons

- name: Installing and configuring Hadoop-yarn cluster
  remote_user: root
  hosts: 
    - master
    - slaves
  roles:
    - {role: yarn, is_master: True, when: "ansible_hostname == '{{ hostvars[groups['master'][0]].inventory_hostname_short}}' and choose_role == 'yarn'"}
    - {role: yarn, is_slave: True, when: "ansible_hostname != '{{ hostvars[groups['master'][0]].inventory_hostname_short}}' and choose_role == 'yarn'"}

- name: Format cluster (if needed) and start the Hadoop-yarn daemons
  remote_user: root
  hosts:
    - master
    - slaves
  tasks:
     - { include: start_yarn.yml, is_master: True, when: "ansible_hostname == '{{ hostvars[groups['master'][0]].inventory_hostname_short}}' and manage_cluster == 'yarn'"}
     - { include: start_yarn.yml, is_slave: True, when: "ansible_hostname != '{{ hostvars[groups['master'][0]].inventory_hostname_short}}' and manage_cluster == 'yarn'"}

- name: Installing and configuring Cloudera cluster
  remote_user: root
  hosts:
    - master_cloud
    - slaves_cloud
  roles:
    - {role: cloudera, is_master: True, when: "ansible_hostname == '{{ hostvars[groups['master_cloud'][0]].inventory_hostname_short}}' and choose_role == 'cloudera'"}
    - {role: cloudera, is_slave: True, when: "ansible_hostname != '{{ hostvars[groups['master_cloud'][0]].inventory_hostname_short}}' and choose_role == 'cloudera'"}

- name: Format Cloudera cluster (if needed) and start the Hadoop cloudera daemons
  remote_user: root
  hosts:
    - master_cloud
    - slaves_cloud
  tasks:
     - { include: start_cloudera.yml, is_master: True, when: "ansible_hostname == '{{ hostvars[groups['master_cloud'][0]].inventory_hostname_short}}' and manage_cluster == 'cloudera'"}
     - { include: start_cloudera.yml, is_slave: True, when: "ansible_hostname != '{{ hostvars[groups['master_cloud'][0]].inventory_hostname_short}}' and manage_cluster == 'cloudera'"}

- name: Setup orka_admin user in Django server
  hosts: webserver
  remote_user: root
  tasks:
     - { include: setup_orka_admin.yml, when: create_orka_admin == 'True' and choose_role == 'webserver'}

- name: Installing and configuring Django server
  hosts: webserver
  remote_user: orka_admin
  roles:
     - {role: webserver, when: choose_role == 'webserver'}
